FROM mcr.microsoft.com/dotnet/runtime:5.0-nanoserver-20H2 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-nanoserver-20H2 AS build
WORKDIR /src
COPY ["Jigbot/Jigbot.csproj", "Jigbot/"]
RUN dotnet restore "Jigbot/Jigbot.csproj"
COPY . .
WORKDIR "/src/Jigbot"
RUN dotnet build "Jigbot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Jigbot.csproj" -c Release -o /app/publish

FROM base AS final
ENV Token=""
ENV Command=""
ENV URIBASE=""
ENV UPLOADS=""
VOLUME /jigbot/uploads
VOLUME /jigbot/images
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Jigbot.dll"]